version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fileconverter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 fileconverter.asgi:application"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fileconverter
  
  celery:
    build: .
    command: celery -A fileconverter worker --loglevel=info
    volumes:
      - ./media:/app/media
    depends_on:
      - redis
      - db
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fileconverter
  
  celery-beat:
    build: .
    command: celery -A fileconverter beat --loglevel=info
    depends_on:
      - redis
      - db
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fileconverter

volumes:
  postgres_data:
  redis_data:

