# Generated by Django 4.2.25 on 2025-10-26 12:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='converted/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_format', models.CharField(max_length=10)),
                ('target_format', models.CharField(max_length=10)),
                ('conversion_type', models.CharField(choices=[('image', 'Image Conversion'), ('document', 'Document Conversion'), ('video', 'Video Conversion')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('converted_file_size', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='converter_f_status_5c754e_idx'), models.Index(fields=['conversion_type'], name='converter_f_convers_042d40_idx')],
            },
        ),
    ]
